# Required
[[plugins]]
repo = 'Shougo/dein.vim'


# ColorSchemes
[[plugins]]
repo = 'flazz/vim-colorschemes'


# Display
[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


# Filer
[[plugins]]
repo = 'scrooloose/nerdtree'


# Utility
[[plugins]]
repo = 'cohama/lexima.vim'


# Status bar
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'


# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

