# Vim8
[[plugins]]
repo    = 'roxma/nvim-yarp'
on_if   = '!has("nvim")'
depends = ['vim-hug-neovim-rpc']

[[plugins]]
repo  = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'


# JavaScript
[[plugins]]
repo  = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo  = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo    = 'othree/es.next.syntax.vim'
on_ft   = ['javascript', 'javascript.jsx']
depends = ['yajs.vim']

[[plugins]]
repo  = 'moll/vim-node'
on_ft = ['javascript']
